//
//  GlobalConstant.swift
//  TimeControllApp
//
//  Created by Abhishek on 02/07/22.
//

import Foundation
import UIKit

//MARK: - STORYBOARD
struct STORYBOARD {
    static let MAIN = UIStoryboard(name: "Main", bundle: nil)
    static let HOME = UIStoryboard(name: "Home", bundle: nil)
    static let WORKHOURS = UIStoryboard(name: "WorkHour", bundle: nil)
    static let FILES = UIStoryboard(name: "MyFiles", bundle: nil)
    static let DOCUMENTS = UIStoryboard(name: "Documents", bundle: nil)
    static let PROFILE = UIStoryboard(name: "Profile", bundle: nil)
    static let  AVAILABILITY = UIStoryboard(name: "Availability", bundle: nil)
}

//MARK: - SCREEN
struct SCREEN
{
    static var WIDTH = UIScreen.main.bounds.size.width
    static var HEIGHT = UIScreen.main.bounds.size.height
}

//MARK: - UserDefaultKeys
struct UserDefaultKeys {
    static let userId = "currentUser"
    static let token = "accessToken"
    static let userImageId = "currentUserImageId"
    static let userName = "currentUserName"
    static let userType = "currentUserType"
    static let clientImage = "clientImage"
    static let clientId = "clientId"
    static let userImageIdAPI = "currentUserImageIdAPI"
    static let selectedLanguageCode = "selectedLanguageCode"
    static let clientName = "clientName"

    static let fcmToken = "fcmToken"
    static let deviceID = "deviceID"
    static let notificationData = "notificationData"

    static let userFullname = "userFullname"
    
    static let checkWorkHoursDetails = "checkWorkHoursDetails"
    
    static var expenseTypes = [String]()
    static var extraWork = [String]()
    
    static let serverChangeURL = "serverChangeURL"
}




class Helper {
    static func minutesToHoursAndMinutes(_ minutes: Int) -> (hours: Int , leftMinutes: Int) {
        return (minutes / 60, (minutes % 60))
    }
    
    class func urlParameterForPagination() -> [String : Any] {
        
        var dict : [String : Any] = [:]
        
        dict = ["pagesize" : 10,"page" : GlobleVariables.page]
        return dict
        
    }
}


struct GlobleVariables  {
    
    static var arrOvertimeTypes = [AnyObject]()
    
    static var page = 0
    
    static var isoFormatter = ISO8601DateFormatter()
    
    static  var clientControlPanelConfiguration : ClientModel?
    static  var bizTypeControlPanelConfiguration : BiztypeModel?
    static  var integrationDetailsControlPanelConfiguration : Integration_details?
    static  var timezoneGMT : Int?
    static  var isObligatoryDocuments = true
    static var countryCodeFromLocation = ""
    static var dynamicBaseUrl = "https://tidogkontroll.no/api/"
    
    static var notificationCount = 0
}

//MARK: - LocalizationKey
struct LocalizationKey {
    static var thu = "Thu";
    static var enterDateOfBirth = "Enter Date of birth";
    static var includeMileAllowanceFromHomeAddress = "Include mile allowance from home address";
    static var documents = "Documents";
    static var cancel = "Cancel";
    static var save = "Save";
    static var areYouSureYouWantTo = "Are you sure you want to";
    static var areYouSureYouWantToDeleteRelative = "Are you sure you want to delete relative?";
    static var uploadDocuments = "Upload Documents";
    static var allWorkingDays = "All Working Days";
    static var normal = "Normal";
    static var password = "Password";
    static var projectName = "Project Name";
    static var address = "Address";
    static var onTime = "On Time";
    static var urgent = "Urgent";
    static var critical = "Critical";
    static var enterAddress = "Enter address";
    static var changePassword = "Change Password";
    static var enterPhone = "Enter phone";
    static var gPSLocation = "GPS Location";
    static var wed = "Wed";
    static var taskName = "Task name";
    static var postPlace = "Post place";
    static var selectEmployee = "Select employee";
    static var hourlyFixedRate = "Hourly/Fixed Rate";
    static var chef = "Chef";
    static var apply = "Apply";
    static var pleaseLoginToContinue = "Please login to continue";
    static var changeSignature = "Change Signature";
    static var done = "Done";
    static var lastWorkLog = "Last Work Log";
    static var selectDate = "Select Date";
    static var schedule = "Schedule";
    static var selected = "Selected";
    static var selectDocument = "Select Document";
    static var enterCost = "Enter Cost";
    static var enterValue = "Enter Value*";
    static var chat = "Chat";
    static var registerManually = "Register Manually";
    static var search = "Search";
    static var paymentTerms = "Payment Terms";
    static var none = "None";
    static var verify = "Verify";
    static var select = "Select";
    static var registerVacation = "Register Vacation";
    static var enterFileName = "Enter file Name";
    static var assignProjects = "Assign Project(s)";
    static var lastName = "Last Name";
    static var weHaveSentYouAOneTimePasswordAtYourRegisteredPhoneNumber = "We have sent you a one time password at your registered email.";
    static var axis = "Axis";
    static var pin = "Pin";
    static var about = "About";
    static var endDate = "End Date";
    static var selectProject = "Select Project";
    static var email = "Email";
    static var firstName = "First Name";
    static var userRole = "User Role";
    static var indian = "Indian";
    static var gender = "Gender";
    static var mobile = "Mobile";
    static var prashantSiddhpura = "Prashant Siddhpura";
    static var to = "To";
    static var from = "from";
    static var selectChecklist = "Select Checklist";
    static var numberOfHolidays = "Number of Holidays";
    static var uploadedDocuments = "Uploaded Documents";
    static var allMembersEmployees = "All members/employees";
    static var brewBros = "1311 | BrewBros";
    static var deviations = "Deviations";
    static var sSN = "SSN";
    static var attachmentS = "Attachment(s)";
    static var addKid = "Add Kid";
    static var earthmovingEquipments = "Earthmoving equipments...";
    static var postNumber = "Post Number";
    static var confirmNewPassword = "Confirm New Password";
    static var updateAvailabilty = "Update Availabilty";
    static var newRequests = "New Requests";
    static var mySwapsTrades = "My Swaps - Trades";
    static var yes = "Yes";
    static var copyWeek = "Copy Week";
    static var dateOfBirth = "Date of birth";
    static var timeRegistration = "Time Registration";
    static var deactivateUser = "Deactivate User";
    static var checkAvailability = "Check Availability";
    static var employmentType = "Employment Type";
    static var deviationAttachments = "Deviation Attachments";
    static var leaveTheFieldToBeFilledAutomatically = "Leave the field to be filled automatically";
    static var endLocation = "End Location";
    static var sendToThisEmail = "Send to This Email";
    static var logout = "Logout";
    static var weekly = "Weekly";
    static var termsCondition = "Terms & Condition";
    static var daily = "Daily";
    static var monthly = "Monthly";
    static var taskInfo = "Task Info";
    static var vacation = "Vacation";
    static var absence = "Absence";
    static var anomalies = "Anomalies";
    static var sickLeave = "Sick Leave";
    static var registerMiles = "Register Miles";
    static var enterLastName = "Enter Last Name";
    static var subject = "Subject";
    static var estimatedHours = "Estimated Hours";
    static var zipCode = "Zip code";
    static var enterFirstName = "Enter First Name";
    static var nationality = "Nationality";
    static var workHoursPerWeek = "Work Hours Per Week";
    static var weekDays = "Week Days";
    static var accountNumber = "Account Number";
    static var comment = "Comment";
    static var create = "Create";
    static var name = "Name";
    static var project = "Project";
    static var howToCorrect = "How to correct?";
    static var login = "Login";
    static var enterUrgency = "Enter Urgency";
    static var hourly = "Hourly";
    static var enterYourEmail = "Enter your Email";
    static var iMessage = "iMessage";
    static var loremIpsumProject = "Lorem ipsum project";
    static var deviationControl = "Deviation Control";
    static var fullProfile = "Full Profile";
    static var extraPassenger = "Extra Passenger";
    static var chooseTypeOfExtraWork = "Choose Type of Extra Work";
    static var employeePayrollReport = "Employee Payroll Report";
    static var workHours = "Work Hours";
    static var userType = "User Type";
    static var checklist = "Checklist";
    static var attachments = "Attachments";
    static var approve = "Approve";
    static var expensesType = "Expenses Type";
    static var enableAutoLog = "Enable Auto-Log";
    static var costAndExpenses = "Cost and Expenses";
    static var chandigarh = "Chandigarh";
    static var registeredVacations = "Registered Vacations";
    static var offSite = "Off site";
    static var employeeID = "Employee ID";
    static var newPassword = "New Password";
    static var showWeekendHours = "Show weekend hours";
    static var startAnomalies = "Start Anomalies";
    static var users = "Users";
    static var hours = "Hours";
    static var laptop = "Laptop";
    static var distance = "Distance";
    static var reassign = "Reassign";
    static var button = "Button";
    static var signature = "Signature";
    static var notPaid = "Not Paid";
    static var reset = "Reset";
    static var phoneNumber = "Phone Number";
    static var accept = "Accept";
    static var despoUnit = "Despo Unit";
    static var enterPhoneNumber = "Enter Phone Number";
    static var bankInformation = "Bank Information";
    static var preview = "Preview";
    static var employmentGrade = "Employment Grade";
    static var payrollReport = "Payroll Report";
    static var equipment = "Equipment";
    static var reject = "Reject";
    static var kidsInfo = "Kids Info";
    static var successfullyCopiedWithCurrentWeekToNextWeek = "Successfully copied with current week to next week.";
    static var employee = "Employee";
    static var toDate = "To Date";
    static var taskInfoLbl = "TASK INFO";
    static var showAllProjects = "Show all projects";
    static var no = "No";
    static var employmentGradeIn = "Employment Grade In %";
    static var enterPhoneNUMBER = "Enter Phone NUMBER";
    static var enterYourPassword = "Enter your Password";
    static var allRightReservedByTimeControl = "All right reserved by Time & Control";
    static var notVerify = "Not Verify";
    static var verified = "Verified";
    static var vacationsAbsents = "Vacations & Absents";
    static var assign = "Assign";
    static var selectLocation = "Select Location";
    static var phone = "Phone";
    static var equipmentS = "Equipment(s)";
    static var enterEstimatedHours = "Enter estimated hours";
    static var andrewChadwick = "Andrew Chadwick";
    static var deviationSubject = "Deviation Subject";
    static var viewDetails = "View Details";
    static var howToStopItHappenAgain = "How to stop it happen again?";
    static var notifications = "Notifications";
    static var patel = "Patel";
    static var paid = "Paid";
    static var uploadFiles = "Upload Files";
    static var enterDeviation = "Enter Deviation";
    static var documentsAndContractS = "Document(s) and Contract(s)";
    static var closestRelative = "Closest Relative";
    static var thankYouForTakingTheShiftTheManagerHasBeenInformedPleaseWaitForTheApproval = "Thank you for taking the shift; the manager has been informed. Please wait for the approval.";
    static var startDate = "Start Date";
    static var medicalLeave = "Medical Leave";
    static var pending = "Pending";
    static var new = "New";
    static var underWork = "Under Work";
    static var sendEmail = "Send Email";
    static var ifYouWantToAddTheClosestRelativePleaseClickOnTheAboveAddButtonToAddThem = "If you want to add the closest relative please\nclick on the above add button to add them.";
    static var endOfTheDay = "End of the Day";
    static var extraWork = "Extra Work";
    static var male = "Male";
    static var passengerName = "Passenger Name";
    static var personalInformation = "Personal Information";
    static var typeOfExtraWork = "Type of Extra Work";
    static var enterDueDate = "Enter due date";
    static var finish = "Finish";
    static var enterPin = "Enter Pin";
    static var availability = "Availability";
    static var clear = "Clear";
    static var city = "City";
    static var alexPostinikov = "Alex Postinikov";
    static var dashboard = "Dashboard";
    static var gPSData = "GPS Data";
    static var restVacations = "Rest Vacations";
    static var norsktimeregisterNo = "norsktimeregister.no";
    static var addRelative = "Add Relative";
    static var add = "Add";
    static var nameInTheBank = "Name in the Bank";
    static var english = "English";
    static var registerAbsence = "Register Absence";
    static var enterDistance = "Enter Distance";
    static var caughtDeviationDetails = "Caught Deviation Details";
    static var addressInformation = "Address Information";
    static var annually = "Annually";
    static var forgotPassword = "Forgot Password";
    static var seeAll = "See all";
    static var swappingOrTradingYourShiftOnMondayDec199050PM = "Swapping or Trading your shift on";
    static var allowCheckAll = "Allow Check All";
    static var Search = "           Search";
    static var userName = "User Name";
    static var chefRichondRepublic = "Chef; Richond Republic";
    static var read = "Read";
    static var addBonus = "Add Bonus";
    static var upForGrabs = "Up for Grabs";
    static var dueDate = "Due Date";
    static var profile = "Profile";
    static var personalInfo = "Personal Info";
    static var iAmDoingItMyself = "I am doing it myself";
    static var cOSTANDEXPENSES = "COST AND EXPENSES";
    static var female = "Female";
    static var dESCRIPTION = "DESCRIPTION";
    static var mon = "Mon";
    static var year = "Year";
    static var currentPassword = "Current Password";
    static var status = "Status";
    static var disableAutoLog = "Disable Auto-Log";
    static var thankYouForSwappingTradingTheShiftTheEmployeesHasBeenInformedPleaseWaitForTheAcceptance = "Thank you for Swapping-Trading the shift; the Employees has been informed. Please wait for the acceptance.";
    static var extraHours = "Extra Hours";
    static var nameOfTheBank = "Name of the Bank";
    static var settings = "Settings";
    static var totalHours = "Total Hours";
    static var changeLanguage = "Change Language";
    static var thankYouForAcceptingTheRequestTheManagerHasBeenInformedPleaseWaitForTheApproval = "Thank you for accepting the request; the manager has been informed. Please wait for the approval.";
    static var enterProject = "Enter Project";
    static var sendRequest = "Send Request";
    static var selectMemberS = "Select Member(s)";
    static var traklestinget18MountainHill = "Traklestinget; 18; Mountain hill";
    static var atWork = "At Work";
    static var approved = "Approved";
    static var prashantsidd98 = "Prashantsidd98";
    static var spokenLanguageS = "Spoken Language(s)";
    static var member = "Member";
    static var approvedOnly = "Approved only";
    static var andrew = "Andrew";
    static var systemSettings = "System Settings";
    static var enterSubject = "Enter Subject";
    static var createDeviation = "Create Deviation";
    static var obligatory = "Obligatory";
    static var fri = "Fri";
    static var accessInformation = "Access Information";
    static var nr = "nr";
    static var reports = "Reports";
    static var extraPassanger = "Extra Passanger";
    static var gNr = "G.nr";
    static var accepted = "Accepted";
    static var comments = "Comments";
    static var tue = "Tue";
    static var shiftRequests = "Shift Requests";
    static var totalLeaves = "Total Leaves";
    static var gpsData = "Gps Data";
    static var fromDate = "From Date";
    static var pendingRequests = "Pending Requests";
    static var roleDepartment = "Role/Department";
    static var describeHowToPreventIt = "Describe; how to prevent it";
    static var confirmedExtraCaretakeDays = "Confirmed extra caretake days";
    static var enterEmail = "Enter email";
    static var employedSince = "Employed Since";
    static var utilizedLeaves = "Utilized Leaves";
    static var enterYourPassengerName = "Enter your passenger name";
    static var workFinished = "Work Finished";
    static var date = "Date";
    static var selectAShiftToSwapOrTradeWith = "Select a shift to Swap or Trade with";
    static var startLocation = "Start Location";
    static var bNr = "B.nr";
    static var username = "Username";
    static var projectS = "Project(s)";
    static var memberS = "Member(s)";
    static var documentS = "Document(s)";
    static var urgency = "Urgency";
    static var didYouGetAnyInjuryAtSiteToday = "Did you get any injury at site today?";
    static var swapTrades = "Swap – Trades";
    static var delete = "Delete";
    static var deviationDetails = "Deviation Details";
    static var totalVacations = "Total Vacations";
    static var number = "Number";
    static var sun = "Sun";
    static var parentalLeave = "Parental Leave";
    static var send = "Send";
    static var rent = "Rent";
    static var thisWillSendYouAnEmailWithResettedPasswordPleasceCheckInSpamFolderForTheEmail = "This will send you an email with resetted password. Please check in Spam folder for the email.";
    static var enterStartDate = "Enter start date";
    static var estimatedConsequenceOfTheDeviation = "Estimated Consequence of the deviation";
    static var verifyNow = "Verify Now";
    static var sickLeaves = "Sick Leaves";
    static var passangerName = "Passanger Name";
    static var editProfile = "Edit Profile";
    static var leaveType = "Leave Type";
    static var oneTimePassword = "One Time Password";
    static var taskMap = "Task Map";
    static var documentsS = "Documents(s)";
    static var enterExpensesType = "Enter expenses type";
    static var selectFunction = "Select Function";
    static var haveChronicDisease = "Have chronic disease?";
    static var verifyYourPhoneNumber = "Verify your Phone Number";
    static var inspection = "Inspection";
    static var tasks = "Tasks";
    static var enterUsername = "Enter username";
    static var yourGPSLocationIsUsedToAutomaticallyRecordYourWorkingHours = "Your GPS location is used to automatically record your working hours.";
    static var enterTaskName = "Enter task name";
    static var cost = "Cost";
    static var version1 = "Version 1.0";
    static var Checklist = "11 | Checklist";
    static var howDidWeFixThis = "How did we fix this?";
    static var deviation = "Deviation";
    static var endAnomalies = "End Anomalies";
    static var totalToPay = "Total To Pay";
    static var active = "Active";
    static var inactive = "Inactive";
    static var inprogress = "Inprogress";
    static var reportedBy = "Reported By";
    static var gapBetweenDays = "Gap Between Days";
    static var chadwick = "Chadwick";
    static var estimatedCauseOfDeviation = "Estimated cause of deviation";
    static var otherExpenses = "Other Expenses";
    static var selectADate = "Select a Date";
    static var readMoreAboutPrivacyAt = "Read more about privacy at";
    static var enterProjectName = "Enter Project name";
    static var forgotPasswords = "Forgot Password?";
    static var selectTask = "Select Task";
    static var all = "All";
    static var today = "Today";
    static var saveChanges = "Save Changes";
    static var sSM = "SSM";
    static var parentalLeaves = "Parental Leaves";
    static var sat = "Sat";
    static var unassign = "Unassign";
    static var homeLocation = "Home Location";
    static var remindPassword = "Remind Password";
    static var selectDocuments = "Select Documents";
    static var employement = "Employement";
    static var workStarted = "Work Started";
    static var totalDays = "Total Days";
    static var autoLocate = "Auto Locate";
    static var grossRate = "Gross Rate";
    static var describeWhatCanBeDone = "Describe; what can be done";
    static var monday = "Monday";
    static var privacyPolicies = "Privacy Policies";
    static var createShift = "Create Shift";
    static var reportForAllEmployeesCanBeTooBigWeRecommendToSelectOneEmployeeAtATimeAndTry = "Report for all employees can be too big. We recommend to select one employee at a time and try.";
    static var type = "Type";
    static var halfYearly = "Half Yearly";
    static var enterDescription = "Enter Description";
    static var notifyUser = "Notify User";
    static var addTask = "Add Task";
    static var gPSInfo = "GPS Info";
    static var posttPlace = "Postt Place";
    static var showByProjectName = "Show by project name";
    static var enterYourPassangerName = "Enter your passanger name"
    static var rejected = "Rejected"
    static var unPaid = "Unpaid"
    static var days = "Days"
    static var error = "Error"
    static var fromStacic = "From"
    static var alert = "Alert"
    static var polish = "Polish"
    static var lithuanian = "Lithuanian"
    static var greek = "Greek"
    static var norwegian = "Norwegian"
    static var russian = "Russian"
    static var spanish = "Spanish"
    static var swedish = "Swedish"
    static var requestDate = "Request Date"
    static var typeOfLeave = "Type of Leave"
    static var paidVacation = "Paid Vacation"
    static var unpaidVacation = "Unpaid Vacation"
    static var location = "Location:"
    static var missing = "Missing"
    static var stratTime = "Strat time "
    static var play = "Play"
    static var pause = "Pause"
    static var totalTime = "Total Time"
    static var workToBeDoneNow = "Work to be done now"
    static var startwork = "Start Work"
    static var noWorkRightNow = "No work right now"
    static var myTasks = "My Tasks"
    static var doneDate = "Done Date"
    static var createdBy = "Created By"
    static var assignedTo = "Assigned To"
    static var noShift = "No Shift"
    static var swapped = "Swapped"
    static var awaitingPM = "Awaiting PM"
    static var cancelled = "Cancelled"
    static var action = "Action"
    static var camera = "Camera"
    static var user = "user"
    static var signAll = "Sign All"
    static var checkAll = "Check All"
    static var infoFromAdmin = "Info From Admin"
    static var commentByMember = "Comment By Member"
    static var imageFileByMember = "Image/File By Member"
    static var working = "Working"
    static var responsible = "Responsible"
    static var describeConsequenceOfTheDeviation = "Describe consequence of the deviation"
    static var responsibility = "Responsibility"
    static var costAndHours = "Costs and hours"
    static var enterTotalHours = "Enter total hours"
    static var enterHourlyRate = "Enter hourly rate"
    static var otherCost = "Other costs"
    static var total = "Total"
    static var shiftTiming = "Shift Timing"
    static var grabShift = "grab-Shift"
    static var viewAnomaly = "View Anomaly"
    static var offTime = "Off-time"
    static var onTimeAnomaly = "On-time"
    static var offSiteAnomaly = "Off-site"
    static var onSite = "On-site"
    static var time = "Time"
    static var miles = "Miles"
    static var breakData = "Break"
    static var totalHrs = "Total Hrs"
    static var draft = "Draft"
    static var locationGPSTurnedOff =  "Location: GPS turned off"
    static var you = "You"
    static var offSetArea = "Off set area"
    static var noGPS = "No GPS"
    static var manualOffArea = "Manual off area"
    static var startTime = "Start Time"
    static var endTime = "End Time"
    static var breakTime = "Break Time"
    static var finishNow = "Finish Now"
    static var takeBreak = "Take Break"
    static var trackerGpsData = "Tracker/GPS Data"
    static var inTime = "In Time"
    static var outTime = "Out Time"
    static var overtimes = "Overtimes"
    static var passanger = "Passanger"
    static var registerKilometer = "Register Kilometer"
    static var addOn = "Add On"
    static var overtimeHours = "Overtime Hours"
    static var workingHours = "Working Hours"
    static var otherDocuments = "Other Documents"
    static var availabilityType = "Availability Type"
    static var repeating = "Repeating"
    static var selectWeek = "Select Week"
    static var available = "Available"
    static var notAvailable = "Not Available"
    static var allDay = "All Day"
    static var selectAvailability = "Select Availability"
    static var age = "Age"
    static var ifYouWantToAddTheKidsPleaseClickOnTheAboveAddButtonToAddThem = "If you want to add the kids please\nclick on the above add button to add them."
    static var dismiss = "Dismiss"
    static var noAvailability = "No Availability"
    static var grab = "Grab"
    static var awaiting = "Awaiting"
    static var na = "N/A"
    static var da = "D/A"
    static var chooseAnImage = "Choose an image"
    static var gallery = "Gallery"
    static var warning = "Warning"
    static var youdontHaveCamera = "You don't have camera"
    static var ok = "Ok"
    static var close = "Close"
    static var home = "Home"
    static var myFiles = "My Files"
    static var obligatoryDocuments = "Obligatory Documents"
    static var readNow = "Read Now"
    static var readLater = "Read Later"
    static var confirm = "Confirm"
    static var iHaveReadThisDocument = "I have read this document"
    static var registerdVacations = "Registered Vacations"
    static var child = "Child"
    static var selectChild = "Select Child"
    static var files = "Files"
    static var contracts = "Contracts"
    static var internalDOC = "Internal DOC"
    static var addFile = "Add file"
    static var fileName = "File Name"
    static var addInternalFile = "Add Internal File"
    static var addContracts = "Add Contracts"
    static var contractName = "Contract Name"
    static var enterContractName = "Enter Contract Name"
    static var reasonForSwap = "Reason for swap"
    static var resetApproval = "Reset Approval"
    static var emailUsername = "Email / Username"
    static var bankAccount = "Bank Account"
    static var myShift = "My Shift"
    static var colleagueShift = "Colleague Shift"
    static var shiftsClickToSeeMore = "Shifts, Click to see more"
    static var early = "Early"
    static var late = "Late"
    static var doctorClarification = "Doctor Clarification"

    // Messages
    static var pleaseEnterEmail = "Please enter email"
    static var pleaseEnterPassword = "Please enter password"
    static var pleaseEnterValidEmail = "Please enter valid email"
    static var fromDateMustBeLessThenToDate = "The 'from' date must be earlier than the 'to' date"
    static var deletethisChat = "Delete this chat"
    static var noHistoryHasBeenFound = "No history has been found! \n\nPlease add member(s) from the list to send messages!"
    static var pleaseSelectAtLeastTwoMember = "Please select at least two member"
    static var privateRoomCreatedSuccessfully = "Private Room Created Successfully"
    static var success = "Success"
    static var enterTheAddess = "Enter the addess"
    static var enterTheZipcode = "Enter the zipcode"
    static var enterTheCity = "Enter the city"
    static var enterTheComment = "Enter the comment"
    static var enterTheEstimatedWorkHour = "Enter the estimated work hour"
    static var yourTaskUpdated = "Your task updated"
    static var yourTaskCreated = "Your task created"
    static var helloTimeAndControlNoticedThatYouHaventArrivedAtTheSiteYet = "Hello, Time & Control noticed that you haven't arrived at the site yet"
    static var wouldYouStillLikeToClockInForYourShift = "Would you still like to clock in for your shift?"
    static var WhyDoYouWantToStartFromThisLocation = "Why do you want to start from this location?"
    static var reason = "Reason"
    static var pleaseProvideReason = "Please provide a reason"
    static var equipmentAllreadyAvailableInTheList = "Equipment allready available in the list"
    static var LanguageAllreadyAvailableInTheList = "Language allready available in the list"
    static var pleaseEnterName = "Please enter name"
    static var pleaseEnterPhone = "Please enter phone"
    static var notAllowedToDelete = "Not allowed to delete"
    static var yourScheduledTimeIs = "Your scheduled time is"
    static var doYouWantToStartEarlierToday = "Do you want to start earlier today?"
    static var whyDoYouWantToStartEarlierToday = "Why do you want to start earlier today?"
    static var heyYouStillHaveSomeTimeLeftBeforeScheduling = "Hey, you still have some time left before scheduling"
    static var andYouHaventArrivedAtTheSiteYetWWouldYouLikeToBegin = "And you haven't arrived at the site yet. Would you like to begin?"
    static var whyDoYouWantToStartEarlierFromOffSite = "Why do you want to start earlier from off-site?"
    static var lateShift = "Late Shift?"
    static var youAreRunningLateTodayYourPMWillBeInformed = "You are running late today Your PM will be informed."
    static var noCheckListAvailable = "No CheckList Available"
    static var noScheduleAvailable = "No Schedule Available"
    static var swappingOrTradingYourShiftOn = "Swapping or Trading your shift on"
    static var pleaseSelectEmployee = "Please Select Employee"
    static var noEmployeeAvailable = "No Employee Available"
    static var noTradeRequestAvailable = "No Trade Request Available"
    static var areYouSureDoYouWantYouAcceptTheRequest = "Are you sure?\nDo you want you Accept the request?"
    static var areYouSureDoYouWantYouRejectTheRequest = "Are you sure?\nDo you want you reject the request?"
    static var pleaseSelectStartDate = "Please select start date"
    static var pleaseSelectEndDate = "Please select end date"
    static var pleaseSelectProject =  "Please select project"
    static var pleaseSelectTask = "Please select task"
    static var pleaseSelectEmployee2 = "Please select employee"
    static var pleaseSelectStartTime = "Please select start time"
    static var pleaseSelectEndTime = "Please select end time"
    static var pleaseEnterComment = "Please enter comment"
    static var pleaseEnterDeviationSubject = "Please enter deviation subject"
    static var pleaseEnterDeviationDetails = "Please enter deviation details"
    static var checklistDeviationCreatedSuccessfully = "Checklist deviation Created Successfully"
    static var selectProjectChecklistAndEmployee = "Select Project,Checklist and Employee"
    static var pleaseEnterSignature = "Please enter signature"
    static var heyYouStillHaveScheduleTimeLeft = "Hey you still have schedule time left"
    static var doYouWantToGoHomeEarlyToday =  "Do you want to go home early today?"
    static var whyDoYouWanToGoHomeEarlyToday = "Why do you want to go home early today?"
    static var andYouAreNotAtTheWorkSiteWouldYouLikeToProceed =  "And you are not at the work site. Would you like to proceed?"
    static var whyDoYouEantEoEndEarlierFromOffSite = "Why do you want to end earlier from off-site?"
    static var timeControlHasNoticedThatYoureNotAtTheWorkSite = "Time & Control has noticed that you're not at the work site."
    static var doYouStillWantToClockOut = "Do you still want to clock out?"
    static var whyAreYouClockingOutOutsideTheWorkLocation =  "Why are you clocking out outside the work location?"
    static var yourWorkHoursFinished = "Your work hours finished"
    static var pleaseAddProject = "Please add project"
    static var pleaseAddTaskOrProject = "Please add Task or Project"
    static var pleaseAddSubject = "Please add Subject"
    static var pleaseAddDeviationDetails = "Please add Deviation Details"
    static var pleaseAddDueDate = "Please add Due date"
    static var deviationCreatedSuccessfully = "Deviation Created Successfully"
    static var deviationUpdatedSuccessfully = "Deviation updated successfully"
    static var youAreNotUnder500Meter = "You are not under 500 meter."
    static var yourStartTimeIsNotGreaterThanYourEndTime = "Your start time is not greater than your end time"
    static var yourBreakTimeIsNotGreaterThanYourTotalWorkingHours = "Break time must not surpass your total work hours"
    static var pleaseAddTaskAndProject = "Please add task and project"
    static var pleaseSelectTheStartTime = "Please select the start time"
    static var pleaseSelectTheEndTime = "Please select the end time"
    static var confirmTimeChange = "Confirm time change"
    static var youHaveChangedFromtoTimesThisWillSwitchTimelogToManual = "You have changed from/to times, this will switch timelog to manual"
    static var pleaseChooseTypeOfExtraWork = "Please choose type of extra work"
    static var pleaseEnterExtraWorkHour = "Please enter extra work hour"
    static var pleaseAddComment = "Please add comment"
    static var pleaseEnterPassengerName =  "Please enter passenger name"
    static var pleaseEnterDistance = "Please enter distance"
    static var pleaseEnterStartLocation = "Please enter start location"
    static var pleaseEnterStopLocation = "Please enter stop location"
    static var pleaseChooseExpenseType = "Please choose expense type"
    static var pleaseEnterCost = "Please enter cost"
    static var gpsTurnOffByUser = "GPS turn off by user"
    static var weAreGettingSomeProblemFromGooglePleaseTryAgainLater = "We are Getting Some Problem From Google Please Try Again Later"
    static var enterCurrentPassword = "Enter Current Password"
    static var enterNewPassword = "Enter New Password"
    static var newPasswordShoudbesameasConfirmNewPassword = "New Password Shoud be same as Confirm New Password"
    static var ageShouldBeLessThen18OrInValidDate = "Age should be less then 18 or in valid date"
    static var enterThePostNumber = "Enter the Post Number"
    static var enterThePostPlace = "Enter the Post Place"
    static var availabilityRequestAccepted = "Availability Request Accepted"
    static var availabilityRequestRejected = "Availability Request Rejected"
    static var pleaseEnterFromTimeInMonday = "Please enter From time in Monday"
    static var pleaseEnterToTimeInMonday = "Please enter To time in Monday"
    static var pleaseEnterFromTimeInTuesday = "Please enter From time in Tuesday"
    static var pleaseEnterToTimeInTuesday = "Please enter To time in Tuesday"
    static var pleaseEnterFromTimeInWednesday = "Please enter From time in Wednesday"
    static var pleaseEnterToTimeInWednesday = "Please enter To time in Wednesday"
    static var pleaseEnterFromTimeInThursday = "Please enter From time in Thursday"
    static var pleaseEnterToTimeInThursday = "Please enter To time in Thursday"
    static var pleaseEnterFromTimeInFriday = "Please enter From time in Friday"
    static var pleaseEnterToTimeInFriday = "Please enter To time in Friday"
    static var pleaseEnterFromTimeInSaturday = "Please enter From time in Saturday"
    static var pleaseEnterToTimeInSaturday = "Please enter To time in Saturday"
    static var pleaseEnterFromTimeInSunday = "Please enter From time in Sunday"
    static var pleaseEnterToTimeInSunday = "Please enter To time in Sunday"
    static var availabilityCreated = "Availability created"
    static var availabilityUpdated = "Availability updated"
    static var fromTimeShouldBeLesserThanToTime = "From time should be lesser than To time"
    static var toTimeShouldBeBiggerThanFromTime = "To time should be bigger than From time"
    static var pdfSentOnYourEmailId = "PDF sent on your email id"
    static var scheduleCreatedSuccessfully = "Schedule created successfully"
    static var areYouSure = "Are you sure?"
    static var doYouWantToApproveTheRequest = "Do you want to approve the request?"
    static var doYouWantToRejectTheRequest = "Do you want to reject the request?"
    static var vacationApprovedSuccessfully =  "Vacation approved successfully"
    static var vacationRejectedSuccessfully = "Vacation rejected successfully"
    static var absenceApprovedSuccessfully = "Absence approved successfully"
    static var absenceRejectedSuccessfully = "Absence rejected successfully"
    static var pleaseSelectChild = "Please select child"
    static var pleaseSelectAtLeastOneDayOfWeek = "Please select at least one day of week"
    static var pleaseEnterValue = "Please enter value"
    static var pleaseEnterPhoto = "Please enter photo"
    static var absenceCreatedSuccessfully = "Absence created successfully"
    static var vacationCreatedSuccessfully = "Vacation created successfully"
    static var noDeviationAvailable = "No Deviation Available"
    static var noWorkHousAvailable = "No Work Hours Available"
    static var youCanNotSwapPastDate = "You can't swap past shift"
    static var comingSoon = "Coming Soon"
    static var hasWorked = "has worked for"
    static var andTheseTwoEmployeesDoNotHaveTheSameProfession = "And these two employees do not have the same profession"
    static var hoursIncreaseingOvertimeTo = "hours, increaseing overtime to"
    static var hoursThisWeekTheSwapWillChangeHisShiftHoursTo = "hours this week, the swap will change his shift hours to"
    static var doYouStillWantToApproveThisSwapShift = "Do you still want to approve this swap-shift?"
    static var hoursThisWeekTheTradeWillChangeHisShiftHoursTo = "hours this week, the trade will change his shift hours to"
    static var doYouStillWantToApproveThisTradeShift = "Do you still want to approve this trade-shift?"
    static var hoursThisWeekTheGrabWillChangeHisShiftHoursTo = "hours this week, the grab will change his shift hours to"
    static var doYouStillWantToApproveThisGrabShift = "Do you still want to approve this grab-shift?"
    static var swapperName = "Swapper name"
    static var totalHoursAfterSwap = "Total hours after swap"
    static var swapperOvettime = "Swapper ovettime"
    static var acceptorName = "Acceptor name"
    static var acceptorOvettime = "Acceptor overtime"
    static var theseTwoEmployeesDoNotHaveTheSameProfession = "These two employees do not have the same profession"
    static var heyYouAreScheduledToHaveFewerWorkingHoursComparedToTheShiftYouWantToSwapWithYourColleague = "Hey, you are scheduled to have fewer working hours compared to the shift you want to swap with your colleague"
    static var heyYouAreScheduledToHaveMoreWorkingHoursComparedToTheShiftYouWantToSwapWithYourColleague = "Hey, You are scheduled to have more working hours compared to the shift you want to swap with your colleague"
    static var heyYouAreScheduledToHaveFewerWorkingHoursComparedToTheShiftYouWantToTradeWithYourColleague = "Hey, you are scheduled to have fewer working hours compared to the shift you want to trade with your colleague"
    static var heyYouAreScheduledToHaveMoreWorkingHoursComparedToTheShiftYouWantToTradeWithYourColleague = "Hey, You are scheduled to have more working hours compared to the shift you want to trade with your colleague"
    static var andYouAndYourColleagueDoNotHaveTheSameProfession = "And you and your colleague do not have the same profession"
    static var doYouStillWantToGoAhead = "Do you still want to go ahead"
    static var heyYouAndYourColleagueDoNotHaveTheSameProfession = "Hey, you and your colleague do not have the same profession"
    static var doYouStillWantToSwapThisShift = "Do you still want to swap this shift"
    
    // Remaining
    static var totalScheduleHours = "Total scheduled hours"
    static var overtime = "Overtime"
    static var employeesavailablefortradingashift = "Employees available for trading a shift."
    static var theFollowingMembersHaveSentRequestsForTradeGrabOrSwap = "The following members have sent requests for trade, grab, or swap."
    static var employeesAvailableForSwapingAShift = "Employees available for swaping a shift."
    static var day = "day"
    static var week = "week"
    static var month = "month"
    static var hoursThis = "hours this"
    static var theSwapWillChangeTheShiftHoursTo = "The swap-shift will change the shift hours to"
    static var theTradeWillChangeTheShiftHoursTo = "the trade-shift will change the shift hours to"
    static var theGrabWillChangeTheShiftHoursTo = "the grab-shift will change the shift hours to"
    static var resultingInAnOvertimePaymentOf = "resulting in an overtime payment of"
    static var yourEmployerHasMadeGPSUsageMandatoryPleaseTurnOnYourGPS = "Your employer has made GPS usage mandatory. Please turn on your GPS."
    static var allowLocationAccess = "Allow Location Access"
    static var trades = "Trades"
    static var swapes = "Swapes"
    static var others = "Others"
    static var getCurrentLocation = "Get Current Location"
    
    static var areYouSureToResetThis = "Are you sure to reset this?"
    static var areYouSureToApproveThis = "Are you sure to approve this?"
    static var areYouSureToRejectThis = "Are you sure to reject this?"
    static var areYouSureToDeleteThis = "Are you sure to delete this?"
    static var pleaseUploadPhoto = "Please upload photo"
    static var pleaseWriteWhatTasksDidYouDoToday = "Please write, what tasks did you do today?"
    static var areYouSureYouWantToLogout = "Are you sure you want to"
    static var pleaseEnterSickLeaveAmount =  "Please enter sick leave amount"
    static var areYouSureToDeleteAnItem = "Are you sure to delete an item?"
    static var doYouWantToSaveThisHoursToTripletex = "Do you want to save this hours to Tripletex"
    static var heyYouStillHaveSomeTimeLeftBeforeTheScheduledTime = "Hey, you still have some time left before the scheduled time"
    static var andYouHaventArrivedAtTheSiteEitherWouldYouLikeToStart = "And you haven't arrived at the site either. Would you like to start?"
    static var helloTimeAndControlNoticedThatYouHaventArrivedAtTheSiteEither = "Hello, Time & Control noticed that you haven't arrived at the site either"
    static var heyYouAreRunningLateTodayPleasebBeAwareOfThisNextTime = "Hey, you are running late today. Please be aware of this next time"
    static var lateAndOutsideOfWorkLocation = "Late and outside of work location"
    static var wouldYouLikeToStart = "Would you like to start?"
    static var doYouWantToFinishNow = "Do you want to finish now?"
    static var heyYouHaveStillSomeScheduledTimeLeft = "Hey, you have still some scheduled time left"
    static var youAreEndingTheWorkLateToday = "You are ending the work late today"
    static var timeControlHasNoticedThatYoureEndingYourWorkLateTodayPleaseSelectAReasonFromTheNextScreen = "Time & Control has noticed that you're ending your work late today. Please select a reason from the next screen"
    static var andYouHaventArrivedAtTheSiteEitherWouldYouLikeToEnd = "And you haven't arrived at the site either. Would you like to end?"
    static var pleaseSelectASuitableComment = "Please select a suitable comment!"
}
